# Generated by Django 4.2.6 on 2024-05-20 04:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='country_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_for', models.CharField(help_text='Specify who this document is required for (e.g., traveler type)', max_length=200, verbose_name='Document For')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
            },
        ),
        migrations.CreateModel(
            name='VisaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_images/')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visa.country')),
            ],
        ),
        migrations.CreateModel(
            name='VisaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('cancellation_policy', ckeditor.fields.RichTextField()),
                ('visa_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('our_processing_time', models.PositiveIntegerField(blank=True, null=True)),
                ('visa_processing_time', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='visa_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_packages', to='visa.country')),
                ('requirements', models.ManyToManyField(blank=True, related_name='related_documents', through='visa.RequiredDocuments', to='visa.visapackage')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_packages', to='visa.visatype')),
            ],
            options={
                'verbose_name': 'Visa Package',
                'verbose_name_plural': 'Visa Packages',
            },
        ),
        migrations.AddField(
            model_name='requireddocuments',
            name='visa_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visa.visapackage'),
        ),
    ]
