# Generated by Django 4.2.6 on 2024-05-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visapackage',
            name='max_stay',
            field=models.CharField(blank=True, help_text='Maximum stay per entry, e.g., 30 days per entry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visapackage',
            name='number_of_entries',
            field=models.CharField(blank=True, help_text='Number of entries allowed, e.g., single entry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visapackage',
            name='valid_for',
            field=models.CharField(blank=True, help_text='Validity period of the visa, e.g., 90 days after issued', max_length=100, null=True),
        ),
    ]
