# Generated by Django 4.2.14 on 2024-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visabanner',
            name='image',
            field=models.ImageField(upload_to='gallery/visa_images/visa_banner/'),
        ),
        migrations.AlterField(
            model_name='visapackage',
            name='image',
            field=models.ImageField(upload_to='gallery/visa_images/images/'),
        ),
    ]
