# Generated by Django 4.2.6 on 2024-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_visabanner_delete_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visabanner',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
