# Generated by Django 4.2.6 on 2024-06-04 17:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_visatype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visapackage',
            name='refund_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visapackage',
            name='our_processing_time',
            field=models.CharField(blank=True, help_text='Validity period of the visa, e.g., 90 days after issued', max_length=100, null=True),
        ),
    ]
