# Generated by Django 4.2.6 on 2024-05-08 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_alter_visabanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visabanner',
            name='title',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
