# Generated by Django 4.2.6 on 2024-05-08 12:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_alter_visabanner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visapackage',
            name='requirements',
        ),
        migrations.CreateModel(
            name='RequiredDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_for', models.CharField(help_text='Specify who this document is required for (e.g., traveler type)', max_length=200, verbose_name='Document For')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('visa_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visa.visapackage')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
            },
        ),
        migrations.AddField(
            model_name='visapackage',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='related_documents', through='visa.RequiredDocuments', to='visa.visapackage'),
        ),
    ]
