# Generated by Django 4.2.6 on 2024-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_visapackage_general_documents_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visapackage',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_documents', through='visa.RequiredDocuments', to='visa.visapackage'),
        ),
    ]
