# Generated by Django 4.2.6 on 2024-05-16 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='background_videos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Main logo for the site', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for the site', null=True, upload_to='favicons/')),
                ('about_content', ckeditor.fields.RichTextField(blank=True, help_text='Content for the about page', null=True)),
                ('privacy_policy_content', ckeditor.fields.RichTextField(blank=True, help_text='Content for the privacy policy page', null=True)),
                ('terms_of_service', ckeditor.fields.RichTextField(blank=True, help_text='Content for the terms page', null=True)),
                ('cancellation_policy', ckeditor.fields.RichTextField(blank=True, help_text='Content for the cancellation policy page', null=True)),
                ('refund_policy', ckeditor.fields.RichTextField(blank=True, help_text='Content for the refund_policy page', null=True)),
                ('faq', ckeditor.fields.RichTextField(blank=True, help_text='Content for the faq page', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Class name for the icon', max_length=100)),
            ],
        ),
    ]
