# Generated by Django 4.2.6 on 2024-05-25 11:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='backgroundvideo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favicon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={},
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='backgroundvideo',
            name='site',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='site',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the about page.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cancellation_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the cancellation policy page.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the FAQ page.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the privacy policy page.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the refund policy page.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the terms of service page.', null=True),
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
