# Generated by Django 4.2.6 on 2024-05-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the city.', max_length=200)),
                ('country', models.ForeignKey(help_text='Select the country this city belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='SiteSetting.country')),
            ],
        ),
    ]
