# Generated by Django 4.2.14 on 2024-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Upload a background image.', upload_to='gallery/site_images/main_banner/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(help_text='Upload an image representing the country.', upload_to='gallery/site_images/country_images/'),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='image',
            field=models.ImageField(help_text='Upload the favicon for the site.', upload_to='gallery/site_images/favicons/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(help_text='Upload the main logo for the site.', upload_to='gallery/site_images/logo/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload the banner image for the site.', null=True, upload_to='gallery/site_images/main_banner/'),
        ),
    ]
