# Generated by Django 4.2.6 on 2024-05-03 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=ckeditor.fields.RichTextField(help_text='Content for the about page'),
        ),
    ]
