# Generated by Django 4.2.6 on 2024-05-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Class name for the icon.', max_length=100),
        ),
    ]
