# Generated by Django 4.2.6 on 2024-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0002_alter_backgroundimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='site',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload the favicon for the site.', null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the main logo for the site.', null=True, upload_to='logos/'),
        ),
        migrations.DeleteModel(
            name='Favicon',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
