# Generated by Django 4.2.6 on 2024-05-03 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0003_sitesettings_terms_of_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cancellation_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the cancellation policy page', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the refund_policy page', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the about page', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for the site', null=True, upload_to='favicons/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main logo for the site', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the privacy policy page', null=True),
        ),
    ]
