# Generated by Django 4.2.6 on 2024-05-03 14:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_sitesettings_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faq',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for the faq page', null=True),
        ),
    ]
