# Generated by Django 4.2.6 on 2024-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_favicon_logo_remove_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favicon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activate this favicon.'),
        ),
        migrations.AddField(
            model_name='logo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activate this logo.'),
        ),
    ]
