# Generated by Django 4.2.6 on 2024-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0005_favicon_is_active_logo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload the banner image for the site.', null=True, upload_to='banners/'),
        ),
    ]
