# Generated by Django 4.2.6 on 2024-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0005_sitesettings_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='background_videos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
