# Generated by Django 4.2.6 on 2024-05-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0006_sitesettings_banner_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteConfiguration',
        ),
    ]
