# Generated by Django 4.2.6 on 2024-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0007_rename_sitesettings_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload the banner image for the site.', null=True, upload_to='background_images/'),
        ),
    ]
