# Generated by Django 4.2.6 on 2024-05-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0002_city'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='city',
            field=models.ForeignKey(help_text='Select the city where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='SiteSetting.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(help_text='Select the city where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='SiteSetting.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
