# Generated by Django 4.2.14 on 2024-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Upload an image.', upload_to='gallery/tour_images/images/'),
        ),
        migrations.AlterField(
            model_name='tourbanner',
            name='image',
            field=models.ImageField(help_text='Upload a background image for the tour banner.', upload_to='gallery/tour_images/tour_banner/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(help_text='Upload a video.', upload_to='gallery/tour_videos/'),
        ),
    ]
