# Generated by Django 4.2.6 on 2024-05-25 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0002_alter_sociallink_icon_class'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='category',
            field=models.ForeignKey(help_text='Select the category for the tour or event.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tours.category'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='city',
            field=models.ForeignKey(help_text='Select the city where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='SiteSetting.city'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='country',
            field=models.ForeignKey(help_text='Select the country where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='SiteSetting.country'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='places',
            field=models.ManyToManyField(blank=True, help_text='Select the places for the tour or event.', related_name='%(app_label)s_%(class)s_related', to='tours.place'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Select the services included in the tour or event.', related_name='%(app_label)s_%(class)s_related', to='tours.service'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(help_text='Select the location city name.', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='SiteSetting.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(help_text='Select the category for the tour or event.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tours.category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(help_text='Select the city where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='SiteSetting.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(help_text='Select the country where the tour or event will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='SiteSetting.country'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(blank=True, help_text='Select the places for the tour or event.', related_name='%(app_label)s_%(class)s_related', to='tours.place'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Select the services included in the tour or event.', related_name='%(app_label)s_%(class)s_related', to='tours.service'),
        ),
    ]
