# Generated by Django 4.2.6 on 2024-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourbanner_delete_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
