# Generated by Django 4.2.6 on 2024-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_groupevent_city_alter_tour_city_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='<i class="icon-office text-24 text-accent-1"></i>', help_text='Enter the CSS class for the Category icon.', max_length=100),
        ),
    ]
