# Generated by Django 4.2.6 on 2024-05-14 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourbanner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='planned_destinations',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
