# Generated by Django 4.2.6 on 2024-05-16 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visa', '0001_initial'),
        ('bookings', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visabooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visabooking',
            name='visa_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='visa.visapackage'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
